global: 
  scrape_interval: 15s

scrape_configs: 
  - job_name: 'node_exporter'
    static_configs: 
      - targets: [ 'node-exporter:9100' ]

  - job_name: 'website_status'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://13.61.202.190
    relabel_configs:
      - source_labels: [address]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: address
        replacement: blackbox-exporter:9115