name: Deploy Website and Monitoring to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Executing remote ssh commands to deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          if [ ! -d "~/my-devops-website" ]; then
            git clone https://github.com/m67hrtfwg-sys/my-devops-website.git ~/my-devops-website
          fi
          
          cd ~/my-devops-website
          
          git pull origin main
         
          sudo docker stop my-nginx-container || true
          sudo docker rm my-nginx-container || true
          sudo docker run -d --name my-nginx-container -p 80:80 -v $(pwd)/index.html:/usr/share/nginx/html/index.html nginx
      
          sudo docker compose down || true
          sudo docker compose up -d
