name: Deploy Website to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Copy index.html to Server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "index.html"
        target: "/home/ubuntu/website/"

    - name: Executing remote ssh commands to deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |

          sudo docker stop my-nginx-container || true
          sudo docker rm my-nginx-container || true
          sudo docker run -d --name my-nginx-container -p 80:80 -v /home/ubuntu/website:/usr/share/nginx/html nginx
